"""
DARK FACTORY — Gumroad Publisher
Updates existing Gumroad product with latest PDF via API.
Requires: GUMROAD_ACCESS_TOKEN + GUMROAD_PRODUCT_ID in _config/.env
One-time setup: python3 setup_gumroad.py
"""
import os, sys, json, datetime
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent
load_dotenv(BASE_DIR / "_config" / ".env")

import requests

TOKEN      = os.getenv("GUMROAD_ACCESS_TOKEN", "").strip()
PRODUCT_ID = os.getenv("GUMROAD_PRODUCT_ID", "").strip()
OUT_DIR    = BASE_DIR / "_outputs" / "digital_products"


def get_latest_pdf() -> Path | None:
    pdfs = sorted(OUT_DIR.glob("*.pdf"), key=lambda f: f.stat().st_mtime, reverse=True)
    return pdfs[0] if pdfs else None


def get_latest_md_content() -> dict:
    """Extract title + description from latest factory MD output."""
    mds = sorted(OUT_DIR.glob("digital_product_*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
    if not mds:
        return {}
    text = mds[0].read_text(encoding="utf-8")
    lines = [l.strip() for l in text.splitlines() if l.strip()]

    title, description = None, []
    in_desc = False
    for line in lines:
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        elif "TITLE" in line.upper() and "---" not in line:
            # Try to grab title from marketing section
            next_lines = lines[lines.index(line)+1:lines.index(line)+3]
            for nl in next_lines:
                if nl and not nl.startswith("#") and len(nl) < 120:
                    title = nl.strip()
                    break
        elif "DESCRIPTION" in line.upper():
            in_desc = True
        elif in_desc and line.startswith("##"):
            in_desc = False
        elif in_desc:
            description.append(line)

    return {
        "title": title or "Digital Product by Dark Factory",
        "description": "\n".join(description[:30]) if description else "",
    }


def update_product(product_id: str, pdf_path: Path, title: str, description: str, price_cents: int = 1700):
    """Update existing Gumroad product via API."""
    base = f"https://api.gumroad.com/v2/products/{product_id}"
    auth = {"access_token": TOKEN}

    # 1. Update metadata
    print(f"📝 Aktualizuji produkt {product_id}...")
    r = requests.put(base, data={**auth,
        "name":        title[:80],
        "description": description or "Digital product generated by Dark Factory",
        "price":       price_cents,
        "published":   "true",
    })
    data = r.json()
    if not data.get("success"):
        print(f"❌ Metadata update failed: {data.get('message')}")
        return None
    product_url = data["product"].get("short_url") or data["product"].get("url", "")
    print(f"✅ Metadata updated: {product_url}")

    # 2. Upload PDF as content file
    print(f"📎 Nahrávám PDF: {pdf_path.name} ({pdf_path.stat().st_size // 1024}KB)...")
    with open(pdf_path, "rb") as f:
        r2 = requests.post(
            f"https://api.gumroad.com/v2/products/{product_id}/product_files",
            data=auth,
            files={"file": (pdf_path.name, f, "application/pdf")},
        )
    try:
        d2 = r2.json()
        if d2.get("success"):
            print(f"✅ PDF nahráno")
        else:
            print(f"⚠️  PDF upload: {d2.get('message', r2.text[:100])}")
    except Exception:
        print(f"⚠️  PDF upload response: {r2.status_code} {r2.text[:100]}")

    return product_url


def publish():
    if not TOKEN:
        print("❌ GUMROAD_ACCESS_TOKEN není nastaven v _config/.env")
        return None

    if not PRODUCT_ID:
        print("❌ GUMROAD_PRODUCT_ID není nastaven.")
        print("   Spusť: python3 setup_gumroad.py")
        return None

    pdf = get_latest_pdf()
    if not pdf:
        print("❌ Žádné PDF v _outputs/digital_products/")
        return None

    print(f"📦 PDF: {pdf.name}")
    meta = get_latest_md_content()
    title       = meta.get("title", "Digital Product by Dark Factory")
    description = meta.get("description", "")

    url = update_product(PRODUCT_ID, pdf, title, description)
    if url:
        log = OUT_DIR / "published_products.txt"
        with open(log, "a") as f:
            f.write(f"{datetime.datetime.now().isoformat()} — {url} — {pdf.name}\n")
        print(f"\n🎉 LIVE: {url}")
    return url


if __name__ == "__main__":
    publish()
